### ISSUE TITLE
Typographic change: Make "H6" 14 px

### ISSUE THREAD

**Issue by ulde01** [sebgroup/seb-angular-material#14]
**Design change**

**H6**
- Font-size 14
- Font-weight Regular
- Line-height 20
- Color #333333

**Reason**
To be able to differentiate between a primary and secondary headline in a supporting area/box.

**Description**
 https://designlibrary.sebgroup.com/visual-identity/typography/ 

**Examples**
![image](https://user-images.githubusercontent.com/45568194/55565493-35723280-56fa-11e9-93db-30965d852554.png)

Thank you!
/Ulrika

**Comment by ulde01** [comment]
Is this still relevant? If not, feel free to close it with a comment. /Ulrika

**Comment by teraxas** [comment]
We need to check if we need to update typography from visual identity package

**Comment by ulde01** [comment]
Hi @teraxas , how did it go?

**Comment by teraxas** [comment]
We haven't had time to check this yet. As I understand this should be implemented in Visual identity package? If yes, I will create a sepparate issue of updating visual identity package instead.
