### ISSUE TITLE
Updates to typography

### ISSUE THREAD

**Issue by ulde01** [sebgroup/seb-angular-material#2]
See https://github.com/sebgroup/vanilla-pattern-library/issues/2

**Comment by sauliuspaukstys** [comment]
I do not have access to  it :(

**Comment by ulde01** [comment]
Ah, I see. I think that is being worked on. Good that you let me know! Can you see this? https://github.com/sebgroup/design-library/issues/26

Am trying different ways to add design-related issues so that they reach our developers in all the frameworks. It there a way you prefer?
