### ISSUE TITLE
Updated height on Input Field, Drop Down, Medium Button, Segmented Control and Stepper

### ISSUE THREAD

**Issue by ulde01** [sebgroup/seb-angular-material#3]
https://github.sebgroup.com/DesignLibrary/angular-material-pattern-library/issues/24

Thanks!
/Ulrika

**Comment by GabrieleGe** [comment]
Could you provide stepper example? We were not able to find it in http://designlibrary.sebank.se/

**Comment by ulde01** [comment]
That is because it is placed under "Form components"
https://designlibrary.sebgroup.com/components/forms/
![image](https://user-images.githubusercontent.com/45568194/54377159-e732bc00-4684-11e9-9f41-b89156a08be9.png)

**Comment by teraxas** [comment]
> That is because it is placed under "Form components"
> [designlibrary.sebgroup.com/components/forms](https://designlibrary.sebgroup.com/components/forms/)
> ![image](https://user-images.githubusercontent.com/45568194/54377159-e732bc00-4684-11e9-9f41-b89156a08be9.png)

I created a separate issue for Stepper, as it's not part of Angular Material.

Leaving the issue open for now, as after previous changes there are some vertical allignment issues in buttons and dropdowns.

**Comment by teraxas** [comment]
Updated sizes + alignments: https://github.com/sebgroup/seb-angular-material/pull/19
