### ISSUE TITLE
Breadcrumbs (new component)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/seb-angular-material#6]
Breadcrumbs is a new component in Design library:

* Has an SEB-design and a description
* See the details here: http://designlibrary.sebank.se/components/upcoming/breadcrumbs/#usage
* Component identifier: component-breadcrumbs

**Desktop**
![breadcrumb-desktop_2019-02-22](https://user-images.githubusercontent.com/45568194/53254166-1d52d080-36c3-11e9-88f4-086fbbcd927c.jpg)

**Mobile**
![breadcrumb-mobile_2019-02-22](https://user-images.githubusercontent.com/45568194/53254174-22178480-36c3-11e9-8f15-ba99ec85a73a.jpg)

Any questions? Let me know!
/Ulrika

**Comment by GerardasDilda** [comment]
Our library does not contain breadcrumbs, so we think it is not relevant yet.

**Comment by ulde01** [comment]
Ok. I will keep on handing out issues and you can decide what is relevant for you. /Ulrika
