### ISSUE TITLE
CRUD-pattern (new pattern)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/seb-angular-material#75]
**Pattern (sep 2019)**
A pattern that describes a uniform way for the user to add both soft and hard properties. This two-step pattern is especially useful in pages where the user has to manually update values.

A white card triggers a slide-out. Use is the same behaviour for all devices.

**Details**
See the measurements (etc) in Design Library:
https://designlibrary.sebgroup.com/patterns/crud/#usage
Design library identifier: component-crud

![image](https://user-images.githubusercontent.com/45568194/65947963-9aa0a980-e439-11e9-90bf-55d841761efc.png)

Any questions or feedback? /Ulrika, designlibrary@seb.se

**Comment by teraxas** [comment]
Hi, I'll close this issue as this is more pattern of components usage, rather than component itself. Also, we only do theming of components in this project.
