### ISSUE TITLE
Badge (new component)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/seb-angular-material#87]
### Design update 2020-01-13

**What is this?**
This component calls attention to a status/tag/category.
![image](https://user-images.githubusercontent.com/45568194/72283689-95114d00-363f-11ea-952d-556b86833a3e.png)

**Details**
See the specification to get all the right details:
https://designlibrary.sebgroup.com/components/badge/

**Component identifier**
component-badge

Thank you!
/Ulrika

**Comment by teraxas** [comment]
I think we will not do anything about this... My understanding is that there will be some simple class in vanilla package, which can be used.
